#!/usr/bin/env python3
"""Generate TRACKER.md from the front matter of specs/ and tickets/.

Usage:
    python scripts/tracker.py            # regenerate TRACKER.md
    python scripts/tracker.py --check    # validate and fail if TRACKER.md is stale

Standard library only, so it runs without the project's virtualenv. See
specs/README.md for the workflow this supports.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

SPEC_STATUSES = ("draft", "accepted", "implemented", "superseded", "rejected")
TICKET_STATUSES = ("in-progress", "todo", "backlog", "done", "wontfix")
TICKET_TYPES = ("feature", "bug", "chore", "docs", "test")
PRIORITIES = ("P0", "P1", "P2")
OPEN_STATUSES = ("in-progress", "todo", "backlog")

SPEC_KEYS = ("id", "title", "status", "created", "release")
TICKET_KEYS = ("id", "title", "spec", "type", "priority", "status", "release", "created")

SPEC_ID = re.compile(r"^SPEC-\d{3}$")
TICKET_ID = re.compile(r"^ZS-\d{3}$")
DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
RELEASE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")

HEADER = "<!-- Generated by scripts/tracker.py from specs/ and tickets/. Do not edit by hand. -->"


@dataclass
class Item:
    """A spec or ticket parsed from its markdown file."""

    path: Path
    meta: dict[str, str]
    rel: str = field(default="")

    @property
    def id(self) -> str:
        return self.meta.get("id", "")

    def link(self) -> str:
        """Return a markdown link to the item's file."""
        return f"[{self.id}]({self.rel})"


def parse_front_matter(path: Path) -> dict[str, str]:
    """Parse the ``key: value`` front matter block at the top of a markdown file.

    Args:
        path: File to read.

    Returns:
        The front matter as a flat string mapping (empty if there is none).
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    meta: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        key, sep, value = line.partition(":")
        if sep:
            meta[key.strip()] = value.strip()
    return meta


def load(root: Path, folder: str, pattern: str) -> list[Item]:
    """Load every item in ``root/folder`` whose file name matches ``pattern``."""
    directory = root / folder
    if not directory.is_dir():
        return []
    return [
        Item(path=p, meta=parse_front_matter(p), rel=f"{folder}/{p.name}")
        for p in sorted(directory.glob(pattern))
    ]


def release_key(release: str) -> tuple[int, int, int]:
    """Sort key for ``vX.Y.Z`` release strings (unknown formats sort first)."""
    match = RELEASE.match(release)
    if not match:
        return (0, 0, 0)
    major, minor, patch = (int(g) for g in match.groups())
    return (major, minor, patch)


def validate(specs: list[Item], tickets: list[Item]) -> list[str]:
    """Check front matter consistency.

    Returns:
        Human-readable problems; empty when everything is valid.
    """
    errors: list[str] = []
    seen: set[str] = set()

    def check_common(item: Item, keys: tuple[str, ...], id_re: re.Pattern[str]) -> None:
        for key in keys:
            if not item.meta.get(key):
                errors.append(f"{item.rel}: missing '{key}'")
        if not id_re.match(item.id):
            errors.append(f"{item.rel}: malformed id '{item.id}'")
        elif not item.path.name.startswith(f"{item.id}-"):
            errors.append(f"{item.rel}: file name must start with '{item.id}-'")
        if item.id in seen:
            errors.append(f"{item.rel}: duplicate id '{item.id}'")
        seen.add(item.id)
        for key in ("created", "closed"):
            value = item.meta.get(key)
            if value and not DATE.match(value):
                errors.append(f"{item.rel}: '{key}' must be YYYY-MM-DD, got '{value}'")
        if item.meta.get("release") and not RELEASE.match(item.meta["release"]):
            errors.append(f"{item.rel}: release must look like vX.Y.Z")

    for spec in specs:
        check_common(spec, SPEC_KEYS, SPEC_ID)
        if spec.meta.get("status") not in SPEC_STATUSES:
            errors.append(f"{spec.rel}: unknown status '{spec.meta.get('status')}'")

    spec_status = {s.id: s.meta.get("status", "") for s in specs}
    for ticket in tickets:
        check_common(ticket, TICKET_KEYS, TICKET_ID)
        meta = ticket.meta
        status = meta.get("status", "")
        if status not in TICKET_STATUSES:
            errors.append(f"{ticket.rel}: unknown status '{status}'")
        if meta.get("type") not in TICKET_TYPES:
            errors.append(f"{ticket.rel}: unknown type '{meta.get('type')}'")
        if meta.get("priority") not in PRIORITIES:
            errors.append(f"{ticket.rel}: unknown priority '{meta.get('priority')}'")
        closed = bool(meta.get("closed"))
        if status in ("done", "wontfix") and not closed:
            errors.append(f"{ticket.rel}: a {status} ticket needs a 'closed' date")
        if status in OPEN_STATUSES and closed:
            errors.append(f"{ticket.rel}: an open ticket must not have a 'closed' date")
        parent = meta.get("spec", "")
        if parent not in spec_status:
            errors.append(f"{ticket.rel}: unknown spec '{parent}'")
        elif spec_status[parent] == "draft":
            errors.append(f"{ticket.rel}: spec {parent} is still a draft")
        elif (
            spec_status[parent] == "implemented"
            and status in OPEN_STATUSES
            and meta.get("type") != "bug"
        ):
            errors.append(f"{ticket.rel}: spec {parent} is implemented but this ticket is open")
    return errors


def ticket_table(tickets: list[Item], specs_by_id: dict[str, Item]) -> list[str]:
    """Render tickets as a markdown table."""
    rows = [
        "| Ticket | Title | Spec | Type | Priority | Release |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for t in tickets:
        spec = specs_by_id.get(t.meta.get("spec", ""))
        spec_cell = spec.link() if spec else t.meta.get("spec", "")
        rows.append(
            f"| {t.link()} | {t.meta.get('title', '')} | {spec_cell} "
            f"| {t.meta.get('type', '')} | {t.meta.get('priority', '')} "
            f"| {t.meta.get('release', '')} |"
        )
    return rows


def render(specs: list[Item], tickets: list[Item]) -> str:
    """Render the full TRACKER.md document."""
    specs_by_id = {s.id: s for s in specs}
    by_status: dict[str, list[Item]] = {s: [] for s in TICKET_STATUSES}
    for t in tickets:
        by_status.setdefault(t.meta.get("status", ""), []).append(t)

    counts = " · ".join(f"{len(by_status[s])} {s}" for s in TICKET_STATUSES)
    out = [
        "# Tracker",
        "",
        HEADER,
        "",
        "Specs, tickets, and how they flow into each other are described in",
        "[specs/README.md](specs/README.md).",
        "",
        f"**{len(specs)} specs · {len(tickets)} tickets** — {counts}",
        "",
        "## Board",
    ]

    for status, heading in (
        ("in-progress", "In progress"),
        ("todo", "Todo"),
        ("backlog", "Backlog"),
    ):
        items = sorted(by_status[status], key=lambda t: (t.meta.get("priority", ""), t.id))
        out += ["", f"### {heading} ({len(items)})", ""]
        out += ticket_table(items, specs_by_id) if items else ["_None._"]

    closed = by_status["done"] + by_status["wontfix"]
    out += ["", f"### Done ({len(closed)})"]
    releases = sorted({t.meta.get("release", "") for t in closed}, key=release_key, reverse=True)
    if not releases:
        out += ["", "_None._"]
    for release in releases:
        items = sorted((t for t in closed if t.meta.get("release") == release), key=lambda t: t.id)
        out += [
            "",
            "<details>",
            f"<summary>{release} — {len(items)} tickets</summary>",
            "",
            *ticket_table(items, specs_by_id),
            "",
            "</details>",
        ]

    out += ["", "## Specs", ""]
    if not specs:
        out.append("_None._")
    else:
        out += [
            "| Spec | Title | Status | Release | Tickets done |",
            "| --- | --- | --- | --- | --- |",
        ]
        for s in specs:
            own = [t for t in tickets if t.meta.get("spec") == s.id]
            done = sum(t.meta.get("status") in ("done", "wontfix") for t in own)
            out.append(
                f"| {s.link()} | {s.meta.get('title', '')} | {s.meta.get('status', '')} "
                f"| {s.meta.get('release', '')} | {done}/{len(own)} |"
            )
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns a process exit code."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate front matter and fail if TRACKER.md is out of date",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root (default: the parent of scripts/)",
    )
    args = parser.parse_args(argv)

    root: Path = args.root
    specs = load(root, "specs", "SPEC-*.md")
    tickets = load(root, "tickets", "ZS-*.md")

    errors = validate(specs, tickets)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    target = root / "TRACKER.md"
    content = render(specs, tickets)
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != content:
            print(
                "error: TRACKER.md is out of date; run `python scripts/tracker.py`",
                file=sys.stderr,
            )
            return 1
        print(f"TRACKER.md is up to date ({len(specs)} specs, {len(tickets)} tickets).")
        return 0

    target.write_text(content, encoding="utf-8")
    print(f"Wrote TRACKER.md ({len(specs)} specs, {len(tickets)} tickets).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
